Repository cse110-sp23-group15/cse110-sp23-group15, pull requests merged in 2023-06, with the labels that each got.

#90 test: update test cases
  fortunetelling/src/__test__/e2e/navigate.test.js
  fortunetelling/src/__test__/e2e/profile.test.js
  fortunetelling/src/__test__/e2e/questionnaire.test.js
  fortunetelling/src/__test__/screenshots/Galaxy-Chicken-Soup.png
  fortunetelling/src/__test__/screenshots/iPhoneX-questionnaire.png
  fortunetelling/src/__test__/screenshots/tworadioselected-questionnaire.png
Labels: backend

#97 test: add tests for accessibility and fortune
  fortunetelling/src/__test__/e2e/accessibility.test.js
  fortunetelling/src/__test__/e2e/fortune.test.js
  fortunetelling/src/__test__/e2e/profile.test.js
  fortunetelling/src/__test__/e2e/sample.test.js
  fortunetelling/src/__test__/screenshots/Galaxy-Chicken-Soup.png
  fortunetelling/src/__test__/screenshots/allradioselected-questionnaire.png
  fortunetelling/src/__test__/screenshots/fortune-PadThai.png
  fortunetelling/src/__test__/screenshots/fortune-Pho.png
  fortunetelling/src/__test__/screenshots/iPhoneX-questionnaire.png
Labels: backend

#118 test: update tests for questionnaire
  fortunetelling/src/__test__/e2e/accessibility.test.js
  fortunetelling/src/__test__/e2e/questionnaire.test.js
  fortunetelling/src/__test__/screenshots/allradioselected-questionnaire.png
  fortunetelling/src/__test__/screenshots/random-answer.png
  fortunetelling/src/__test__/unit/testPersonality.js
Labels: backend

#130 126 add link to questionnaire in header and dropdown
  fortunetelling/src/css/index.css
  fortunetelling/src/css/main.css
  fortunetelling/src/pages/about.html
  fortunetelling/src/pages/fortune.html
  fortunetelling/src/pages/noodlesResults.html
  fortunetelling/src/pages/profiles.html
Labels: frontend

#143 test: add tests for checking quiz taken
  fortunetelling/src/__test__/e2e/accessibility.test.js
  fortunetelling/src/__test__/e2e/miscellaneous.test.js
  fortunetelling/src/__test__/screenshots/button-text.png
Labels: backend

#146 feat(frontend): Make questions appear one at a time. Add progress bar
  fortunetelling/src/css/main.css
  fortunetelling/src/css/questionnaire.css
  fortunetelling/src/js/questionnaire.js
  fortunetelling/src/pages/questionnaire.html
Labels: enhancement, frontend

#148 Prefetch all asset files in every page to speed up render blocking
  fortunetelling/index.html
  fortunetelling/src/__test__/e2e/README.md
  fortunetelling/src/css/navbar.css
  fortunetelling/src/css/noodlesResults.css
  fortunetelling/src/css/talk.css
  fortunetelling/src/js/noodlesResults.js
  fortunetelling/src/js/transition.js
  fortunetelling/src/js/utils.js
  fortunetelling/src/pages/about.html
  fortunetelling/src/pages/fortune.html
  fortunetelling/src/pages/noodlesResults.html
  fortunetelling/src/pages/profiles.html
  fortunetelling/src/pages/questionnaire.html
Labels: enhancement, frontend
