Repository cse110-sp23-group15/cse110-sp23-group15, pull requests merged in 2023-05, with the labels that each got.

#49 Drafted a mobile first landing page
  fortunetelling/index.html
  fortunetelling/src/css/main.css
  fortunetelling/src/img/icon.png
  fortunetelling/src/img/ramen-icon-1.png
  fortunetelling/src/pages/about.html
  fortunetelling/src/pages/profiles.html
  fortunetelling/src/pages/questionnaire.html
Labels: frontend

#50 Some exploration of testing
  fortunetelling/package-lock.json
  fortunetelling/package.json
  fortunetelling/src/__test__/README.md
  fortunetelling/src/__test__/samplejest.test.js
  fortunetelling/src/__test__/samplemobiletest.js
  fortunetelling/src/__test__/sampleunit.test.js
Labels: frontend, backend

#51 Build lint html css mark
  admin/cipipeline/phase1.drawio.png
  admin/cipipeline/phase1.md
  fortunetelling/.eslintignore
  fortunetelling/.eslintrc.json
  fortunetelling/.husky/pre-commit
  fortunetelling/.prettierignore
  fortunetelling/.prettierrc.json
  fortunetelling/.stylelintrc.json
  fortunetelling/jsdoc.json
  fortunetelling/package-lock.json
  fortunetelling/package.json
Labels: build

#52 Puppeteer simulation of mobile devices
  fortunetelling/src/__test__/samplejest.test.js
  fortunetelling/src/__test__/screenshots/iPhoneX-questionnaire.png
Labels: frontend, backend

#65 added noodle descriptions
  fortunetelling/index.html
  fortunetelling/src/__test__/samplejest.test.js
  fortunetelling/src/__test__/sampleunit.test.js
  fortunetelling/src/css/main.css
  fortunetelling/src/js/database/horoscopeDb.json
  fortunetelling/src/js/database/noodleDescriptions.json
  fortunetelling/src/js/genHoroscope.js
  fortunetelling/src/pages/about.html
  fortunetelling/src/pages/profiles.html
  fortunetelling/src/pages/questionnaire.html
Labels: backend

#72 admin: add meeting minutes for sprint review
  admin/meetings/05-28-2023_sprint-1-review.md
Labels: admin

#71 Switched to a simple custom unit testing framework
  fortunetelling/.eslintrc.json
  fortunetelling/package-lock.json
  fortunetelling/package.json
  fortunetelling/src/__test__/questionnaire.test.js
  fortunetelling/src/__test__/sampleunit.test.js
  fortunetelling/src/__test__/screenshots/iPhoneX-questionnaire.png
  fortunetelling/src/__test__/screenshots/tworadioselected-questionnaire.png
  fortunetelling/src/__test__/unit/helper.js
  fortunetelling/src/__test__/unit/testAll.js
  fortunetelling/src/__test__/unit/testGenHoroscope.js
  fortunetelling/src/__test__/unit/testUtils.js
  fortunetelling/src/js/database/horoscopeDb.json
  fortunetelling/src/js/database/noodleDescriptions.json
  fortunetelling/src/js/genHoroscope.js
  fortunetelling/src/js/main.js
  fortunetelling/src/js/sampleJSDocUsage.js
  fortunetelling/src/js/utils.js
Labels: enhancement, backend, build

#78 Backend unit henry
  fortunetelling/package-lock.json
  fortunetelling/package.json
  fortunetelling/src/__test__/e2e/README.md
  fortunetelling/src/__test__/e2e/profile.test.js
  fortunetelling/src/__test__/e2e/questionnaire.test.js
  fortunetelling/src/__test__/e2e/samplejest.test.js
  fortunetelling/src/__test__/e2e/samplemobiletest.js
  fortunetelling/src/__test__/questionnaire.test.js
  fortunetelling/src/__test__/sampleunit.test.js
  fortunetelling/src/__test__/unit/testPersonality.js
  fortunetelling/src/__test__/unit/testSpeechify.js
Labels: backend
